FROM ubuntu:20.04

WORKDIR /home

RUN apt-get update && apt-get install -y python3 python3-pip git && rm -rf /var/lib/apt/lists/*

COPY alfred_build/ubuntu20.04/alfred.deb .

RUN cd /usr/src
RUN git clone https://github.com/maximofn/alfred.git /usr/src

RUN chmod +x alfred.deb 
RUN dpkg -i alfred.deb
RUN rm alfred.deb
# CMD ["alfred"]
