FROM ubuntu:20.04

WORKDIR /home

RUN apt-get update && apt-get install -y python3 python3-pip python3-setuptools python3-wheel python3-venv python3-dev python3-pip python3-setuptools python3-wheel python3-venv python3-dev
RUN apt-get update && apt-get install -y git

COPY alfred_build/ubuntu20.04/alfred.deb .

RUN chmod +x alfred.deb 
# RUN dpkg -i alfred.deb
# CMD ["alfred"]
