FROM ubuntu:20.04

WORKDIR /home

RUN apt-get update && apt-get install -y python3 python3-pip git && rm -rf /var/lib/apt/lists/*

COPY alfred_build/debian/alfredv1_3.deb .

RUN cd /usr/src
RUN git clone https://github.com/maximofn/alfred.git /usr/src

RUN chmod +x alfredv1_3.deb 
RUN dpkg -i alfredv1_3.deb
RUN rm alfredv1_3.deb
# CMD ["alfred"]
