FROM fedora:36

WORKDIR /home

RUN dnf update -y && dnf install -y python3 python3-pip git && dnf clean all

COPY alfred_build/fedora/alfred-1.3-3.fc36.x86_64.rpm .

RUN cd /usr/src && git clone https://github.com/maximofn/alfred.git

RUN chmod +x alfred-1.3-3.fc36.x86_64.rpm 
RUN rpm -i alfred-1.3-3.fc36.x86_64.rpm
RUN rm alfred-1.3-3.fc36.x86_64.rpm