#!/bin/sh

set -e

# Instalar dependencias de Ubuntu
echo "Installing Ubuntu dependencies..."
# apt-get update && apt-get install -y python3 python3-pip python3-setuptools python3-wheel python3-venv python3-dev python3-pip python3-setuptools python3-wheel python3-venv python3-dev git

# Instalar dependencias de Python
echo "Installing Python dependencies..."
/usr/bin/python3 -m pip install halo
/usr/bin/python3 -m pip install --upgrade openai

# Copiar archivos fuentes a /usr/share/alfred
echo "Copying source files to /usr/share/alfred..."
if [ -d "/usr/src/alfred" ]; then
    echo "Removing /usr/share/alfred..."
    rm -r /usr/src/alfred
fi
cd /usr/src
git clone -b branch_v1.3 https://github.com/maximofn/alfred.git
cd /usr/src/alfred
find . -depth -not -name '*.py' -delete

# Crear enlace simbólico para que los usuarios puedan ejecutar el programa escribiendo 'alfred'
echo "Creating symbolic link to /usr/bin/alfred..."
USER=$SUDO_USER
echo 'alias alfred="/usr/src/alfred/alfred.py"' >> /home/$USER/.bashrc